version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melting_app
    working_dir: /var/www
    volumes:
      - ./melting:/var/www
    networks:
      - melting_network
      - red_general

  webserver:
    image: nginx:alpine
    container_name: melting_server
    ports:
      - "8084:80"
    volumes:
      - ./melting:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - melting_network
      - red_general

networks:
  melting_network:
    driver: bridge
  red_general:
    external: true
